"""integration field for connection

Revision ID: fb3167fa0fb7
Revises: 3258b60e537c
Create Date: 2020-04-22 20:52:35.092494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3167fa0fb7'
down_revision = '3258b60e537c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('connection', sa.Column(
    #     'integration', sa.Unicode(length=255), nullable=True))
    # op.alter_column('connection', 'refresh_token',
    #                 existing_type=sa.TEXT(),
    #                 nullable=True)
    # op.alter_column('connection', 'title',
    #                 existing_type=sa.TEXT(),
    #                 nullable=False)
    # op.alter_column('connection', 'token',
    #                 existing_type=sa.TEXT(),
    #                 nullable=True)
    # op.alter_column('connection', 'user_id',
    #                 existing_type=sa.INTEGER(),
    #                 nullable=False)
    # op.create_unique_constraint(
    #     op.f('uq_connection_refresh_token'), 'connection', ['refresh_token'])
    # op.create_unique_constraint(
    #     op.f('uq_connection_token'), 'connection', ['token'])
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_connection_token'),
                       'connection', type_='unique')
    op.drop_constraint(op.f('uq_connection_refresh_token'),
                       'connection', type_='unique')
    op.alter_column('connection', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('connection', 'token',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.alter_column('connection', 'title',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.alter_column('connection', 'refresh_token',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.drop_column('connection', 'integration')
    # ### end Alembic commands ###
