"""init

Revision ID: 277dac49b0f7
Revises: 871b74414ed9
Create Date: 2020-04-06 23:47:18.643536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277dac49b0f7'
down_revision = '871b74414ed9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
