"""init

Revision ID: 871b74414ed9
Revises: 5899f27f265f
Create Date: 2020-04-05 23:27:59.707787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871b74414ed9'
down_revision = '5899f27f265f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_connection')),
    sa.UniqueConstraint('title', name=op.f('uq_connection_title'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection')
    # ### end Alembic commands ###
